<?php
  $index->content .= 
           "\t\t\t<h2>My AAPL stocks investment historic averages</h2><ul><li>Yearly performance projection average: 141.73%<li>Yearly performance projection XIRR() average: 300.04%<li>Total profit: $198.24<li>Total profit per day: $24.78</ul><h2>My Crecer mutual fund investment historic averages</h2><ul><li>Yearly performance projection average: 9.00%<li>Yearly performance projection XIRR() average: 12.74%<li>Total profit: $214.27<li>Total profit per day: $1.16</ul><h2>Investment 1 in AAPL stocks</h2>
<table>
  <tr>
    <th>Cash flow</th>
    <th>Date</th>
  </tr>
  <tr>
    <td>-$6,381.76</td>
    <td>11-Oct-24</td>
  </tr>
  <tr>
    <td>$6,580.00</td>
    <td>19-Oct-24</td>
  </tr>
  <tr>
    <td>XIRR()</td>
    <td>3.0378256559372</td>
  </tr>
  <tr>
    <td>Investment</td>
    <td>$6,381.76</td>
  </tr>
  <tr>
    <td>Return</td>
    <td>$6,580.00</td>
  </tr>
  <tr>
    <td>Profit</td>
    <td>$198.24</td>
  </tr>
  <tr>
    <td>ROI</td>
    <td>3.11%</td>
  </tr>
  <tr>
    <td>Yearly profit projection</td>
    <td>$9,044.70</td>
  </tr>
  <tr>
    <td>Yearly performance projection</td>
    <td>141.73%</td>
  </tr>
  <tr>
    <td>Days</td>
    <td>8</td>
  </tr>
</table>
<h2>Investment 2 in Crecer mutual fund</h2>
<table>
  <tr>
    <th>Cash flow</th>
    <th>Date</th>
  </tr>
  <tr>
    <td>-$2083.76</td>
    <td>28-Jun-2024</td>
  </tr>
  <tr>
    <td>-$1,500.00</td>
    <td>30-Jul-2024</td>
  </tr>
  <tr>
    <td>-$2,317.82</td>
    <td>3-Sep-24</td>
  </tr>
  <tr>
    <td>$6,578.63</td>
    <td>18-Oct-24</td>
  </tr>
  <tr>
    <td>XIRR()</td>
    <td>0.102817493677139</td>
  </tr>
  <tr>
    <td>Investment</td>
    <td>$6,451.93</td>
  </tr>
  <tr>
    <td>Return</td>
    <td>$6,582.44</td>
  </tr>
  <tr>
    <td>Profit</td>
    <td>$130.51</td>
  </tr>
  <tr>
    <td>ROI</td>
    <td>2.02%</td>
  </tr>
  <tr>
    <td>Yearly profit projection</td>
    <td>$425.32</td>
  </tr>
  <tr>
    <td>Yearly performance projection</td>
    <td>6.59%</td>
  </tr>
  <tr>
    <td>Days</td>
    <td>112</td>
  </tr>
</table>
<br />
<h2>Investment 1 in Crecer mutual fund</h2>
<table>
  <tr>
    <th>Cash flow</th>
    <th>Date</th>
  </tr>
  <tr>
    <td>-$250.00</td>
    <td>12-Apr-24</td>
  </tr>
  <tr>
    <td>-$1,750.00</td>
    <td>16-Apr-24</td>
  </tr>
  <tr>
    <td>-$500.00</td>
    <td>7-May-24</td>
  </tr>
  <tr>
    <td>-$500.00</td>
    <td>14-May-24</td>
  </tr>
  <tr>
    <td>-$500.00</td>
    <td>15-May-24</td>
  </tr>
  <tr>
    <td>$3,579.79</td>
    <td>24-Jun-24</td>
  </tr>
  <tr>
    <td>XIRR()</td>
    <td>0.1519099295</td>
  </tr>
  <tr>
    <td>Investment</td>
    <td>$3,500.00</td>
  </tr>
  <tr>
    <td>Return</td>
    <td>$3,579.79</td>
  </tr>
  <tr>
    <td>Profit</td>
    <td>$79.79</td>
  </tr>
  <tr>
    <td>ROI</td>
    <td>2.28%</td>
  </tr>
  <tr>
    <td>Yearly profit projection</td>
    <td>$398.95</td>
  </tr>
  <tr>
    <td>Yearly performance projection</td>
    <td>11.40%</td>
  </tr>
  <tr>
    <td>Days</td>
    <td>73</td>
  </tr>
</table>\n";
?>
