<?php
  $index->content .= 
           "\t\t\t<iframe src=\"https://docs.google.com/spreadsheets/d/e/2PACX-1vSnedM83IJlnIUy0Ttj4DrDrGWCrqhjC_HXUwxa8cv3nmhraprEToUSuy776FLfXewO49AdS_9SQdUH/pubhtml?widget=true&amp;headers=false\ id=\"investment-spreadsheet\" \"></iframe><h2>My [TEST/Simulator] AAPL stock investment historic averages</h2><ul><li>Yearly performance projection average: -38.34%<li>Yearly performance projection XIRR() average: -32.14%<li>Total profit: -$140.76<li>Total profit per day: -$6.70</ul><h2>My Crecer mutual fund investment historic averages</h2><ul><li>Yearly performance projection average: 7.41%<li>Yearly performance projection XIRR() average: 10.14%<li>Total profit: $156.13<li>Total profit per day: $0.78</ul><h2>Investment 1 in [TEST/Simulator] AAPL stock</h2>
<table>
  <tr>
    <th>Cash flow</th>
    <th>Date</th>
  </tr>
  <tr>
    <td>-$6,381.76</td>
    <td>11-Oct-24</td>
  </tr>
  <tr>
    <td>$6,241.00</td>
    <td>1-Nov-24</td>
  </tr>
  <tr>
    <td>XIRR()</td>
    <td>-32.14</td>
  </tr>
  <tr>
    <td>Investment</td>
    <td>$6,381.76</td>
  </tr>
  <tr>
    <td>Return</td>
    <td>$6,241.00</td>
  </tr>
  <tr>
    <td>Profit</td>
    <td>-$140.76</td>
  </tr>
  <tr>
    <td>ROI</td>
    <td>-2.21%</td>
  </tr>
  <tr>
    <td>Yearly profit projection</td>
    <td>-$2,446.54</td>
  </tr>
  <tr>
    <td>Yearly performance projection</td>
    <td>-38.34%</td>
  </tr>
  <tr>
    <td>Days</td>
    <td>21</td>
  </tr>
</table>
<h2>Investment 2 in Crecer mutual fund</h2>
<table>
  <tr>
    <th>Cash flow</th>
    <th>Date</th>
  </tr>
  <tr>
    <td>-$2083.76</td>
    <td>28-Jun-2024</td>
  </tr>
  <tr>
    <td>-$1,500.00</td>
    <td>30-Jul-2024</td>
  </tr>
  <tr>
    <td>-$2,317.82</td>
    <td>3-Sep-24</td>
  </tr>
  <tr>
    <td>-$550.35</td>
    <td>1-Oct-24</td>
  </tr>
  <tr>
    <td>6,528.27</td>
    <td>1-Nov-24</td>
  </tr>
  <tr>
    <td>XIRR()</td>
	<td>0.050911530852317</td>
  </tr>
  <tr>
    <td>Investment</td>
    <td>$6,451.93</td>
  </tr>
  <tr>
    <td>Return</td>
    <td>$6,528.27</td>
  </tr>
  <tr>
    <td>Profit</td>
    <td>$76.34</td>
  </tr>
  <tr>
    <td>ROI</td>
    <td>1.18%</td>
  </tr>
  <tr>
    <td>Yearly profit projection</td>
    <td>$221.14</td>
  </tr>
  <tr>
    <td>Yearly performance projection</td>
    <td>3.43%</td>
  </tr>
  <tr>
    <td>Days</td>
    <td>126</td>
  </tr>
</table>
<br />
<h2>Investment 1 in Crecer mutual fund</h2>
<table>
  <tr>
    <th>Cash flow</th>
    <th>Date</th>
  </tr>
  <tr>
    <td>-$250.00</td>
    <td>12-Apr-24</td>
  </tr>
  <tr>
    <td>-$1,750.00</td>
    <td>16-Apr-24</td>
  </tr>
  <tr>
    <td>-$500.00</td>
    <td>7-May-24</td>
  </tr>
  <tr>
    <td>-$500.00</td>
    <td>14-May-24</td>
  </tr>
  <tr>
    <td>-$500.00</td>
    <td>15-May-24</td>
  </tr>
  <tr>
    <td>$3,579.79</td>
    <td>24-Jun-24</td>
  </tr>
  <tr>
    <td>XIRR()</td>
    <td>0.1519099295</td>
  </tr>
  <tr>
    <td>Investment</td>
    <td>$3,500.00</td>
  </tr>
  <tr>
    <td>Return</td>
    <td>$3,579.79</td>
  </tr>
  <tr>
    <td>Profit</td>
    <td>$79.79</td>
  </tr>
  <tr>
    <td>ROI</td>
    <td>2.28%</td>
  </tr>
  <tr>
    <td>Yearly profit projection</td>
    <td>$398.95</td>
  </tr>
  <tr>
    <td>Yearly performance projection</td>
    <td>11.40%</td>
  </tr>
  <tr>
    <td>Days</td>
    <td>73</td>
  </tr>
</table>\n";
?>